"""Internal LLM-powered session summarization for sidebar memory."""

from __future__ import annotations

import ast
import json
import re
from typing import Protocol, cast

import structlog
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from src.core.client import NovaClient, NovaClientError

logger = structlog.get_logger()

_SUMMARY_SYSTEM_PROMPT = """
You maintain ephemeral session memory for a student-support chatbot.

Return STRICT JSON only with this exact shape:
{
  "profile_facts": ["..."],
  "conversation_overview": ["..."]
}

Rules:
- Match the user's language. Use German for German chats, English for English chats.
- profile_facts:
  - 0 to 6 concise bullets.
  - Capture durable facts, constraints, preferences, and context that matter for future guidance.
  - Prefer explicit or strongly supported facts from the conversation.
  - Do not guess or invent traits.
  - Good examples: "Erstakademikerin", "17 Jahre alt", "Noch in der Schule", "Abi steht bald an", "Arbeitet 20h/Woche", "Interessiert sich für BAföG und Stipendien".
- conversation_overview:
  - 2 to 5 bullets when possible.
  - Summarize the whole conversation so far, not just the last answer.
  - Include enough context that the user could resume the chat later without losing important details.
  - Each bullet can be one or two short sentences if needed.
  - Mention the user's situation, what has already been explained, and any important next-step or open question when relevant.
  - Avoid repeating the same point in different words.
- Keep each bullet easy to scan in a sidebar, but do not make it so short that the meaning becomes vague.
- No markdown, no prose outside JSON, no explanations.
"""

_MAX_SUMMARY_MESSAGES = 16


class SessionSummary(BaseModel):
    """Sidebar-oriented session summary generated by an internal LLM call."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    profile_facts: tuple[str, ...] = Field(default_factory=tuple)
    conversation_overview: tuple[str, ...] = Field(default_factory=tuple)

    @property
    def has_content(self) -> bool:
        return bool(self.profile_facts or self.conversation_overview)


class SessionSummarizer(Protocol):
    """Protocol for any internal session summarizer implementation."""

    def summarize(
        self,
        messages: list[dict],
        *,
        ui_language: str,
        previous_summary: SessionSummary | None = None,
    ) -> SessionSummary:
        """Return profile facts and a conversation overview for the session."""


class SummaryClient(Protocol):
    """Minimal client surface needed by the internal session summarizer."""

    def converse(
        self,
        messages: list[dict],
        system_prompt: str | None = None,
        tool_config: dict | None = None,
        reasoning_effort: str | None = None,
        max_tokens: int = 512,
        temperature: float = 0.0,
        top_p: float = 1.0,
    ) -> dict: ...

    def extract_text(self, response: dict) -> str: ...


class NovaSessionSummarizer:
    """Use Nova to maintain dynamic sidebar memory in the background."""

    def __init__(self, client: SummaryClient | None = None) -> None:
        self.client = client or NovaClient()

    def summarize(
        self,
        messages: list[dict],
        *,
        ui_language: str,
        previous_summary: SessionSummary | None = None,
    ) -> SessionSummary:
        if not messages:
            return previous_summary or SessionSummary()

        trimmed_messages = messages[-_MAX_SUMMARY_MESSAGES:]
        system_prompt = _build_system_prompt(
            ui_language=ui_language,
            previous_summary=previous_summary,
        )

        try:
            response = self.client.converse(
                trimmed_messages,
                system_prompt=system_prompt,
                max_tokens=650,
                temperature=0.1,
                top_p=0.3,
            )
            text = self.client.extract_text(response).strip()
            if not text:
                logger.info("session_summary_empty_response")
                return previous_summary or SessionSummary()
            payload = _extract_json_payload(text)
            summary = SessionSummary.model_validate(payload)
            if summary.has_content:
                return summary
            return previous_summary or summary
        except (NovaClientError, ValidationError, ValueError, json.JSONDecodeError) as exc:
            logger.warning("session_summary_failed", error=str(exc), type=type(exc).__name__)
            return previous_summary or SessionSummary()


def _build_system_prompt(
    *,
    ui_language: str,
    previous_summary: SessionSummary | None,
) -> str:
    lines = [_SUMMARY_SYSTEM_PROMPT.strip()]

    if ui_language == "de":
        lines.append("Use German for every string in the JSON output.")
    else:
        lines.append("Use English for every string in the JSON output.")

    if previous_summary and previous_summary.has_content:
        lines.extend(
            (
                "",
                "You are updating an existing session summary.",
                "Keep earlier facts and context when they still matter.",
                "Only remove or change items when the newer messages make them outdated or incorrect.",
            )
        )
        if previous_summary.profile_facts:
            lines.append("Existing profile_facts:")
            lines.extend(f"- {item}" for item in previous_summary.profile_facts)
        if previous_summary.conversation_overview:
            lines.append("Existing conversation_overview:")
            lines.extend(f"- {item}" for item in previous_summary.conversation_overview)

    return "\n".join(lines)


def _extract_json_payload(text: str) -> dict:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        payload = json.loads(cleaned)
        return cast(dict, payload)
    except json.JSONDecodeError:
        candidate = _extract_json_candidate(cleaned)
        if candidate is None:
            raise

        try:
            payload = json.loads(candidate)
            return cast(dict, payload)
        except json.JSONDecodeError:
            repaired = _repair_json_candidate(candidate)
            if repaired is not None:
                payload = json.loads(repaired)
                return cast(dict, payload)

            literal_payload = ast.literal_eval(candidate)
            if isinstance(literal_payload, dict):
                return cast(dict, literal_payload)
            raise


def _extract_json_candidate(text: str) -> str | None:
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        return None
    return match.group(0)


def _repair_json_candidate(candidate: str) -> str | None:
    repaired = candidate
    repaired = (
        repaired.replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2019", "'")
        .replace("\u2018", "'")
    )
    repaired = re.sub(r",(\s*[}\]])", r"\1", repaired)
    repaired = re.sub(r"\t", " ", repaired)

    if repaired == candidate:
        return None
    return repaired
