"""One-shot helper: write the canonical .env.example for KODA.

Run with: python3 scripts/write_env_example.py
This overwrites .env.example in the repo root.
"""

import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = REPO_ROOT / ".env.example"

LINES = [
    "# ===========================================================================",
    "# KODA - Environment Configuration Template",
    "# ===========================================================================",
    "#",
    "# USAGE",
    "#   cp .env.example .env",
    "#   Edit .env with your values. python-dotenv loads it automatically.",
    "#",
    "# SECURITY",
    "#   - NEVER commit .env to version control (.gitignore already excludes it).",
    "#   - NEVER store real credentials in production via this file. In ECS/Fargate",
    "#     all secrets are injected via AWS Secrets Manager and IAM task roles.",
    "#     This template is for local development only.",
    "#   - Treat AWS_SECRET_ACCESS_KEY like a password: rotate it regularly, use",
    "#     least-privilege IAM policies, never share via chat or email.",
    "#",
    "# REFERENCE",
    "#   config/settings.py   - Python module that reads these variables at startup.",
    "#   docs/ARCHITECTURE.md - Full system design and deployment topology.",
    "#",
    "# ===========================================================================",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# AWS - Region",
    "# ---------------------------------------------------------------------------",
    "# The AWS region where Amazon Bedrock API calls are made.",
    "# Nova 2 Lite is available via the US cross-region inference profile",
    "# (us.amazon.nova-2-lite-v1:0) in us-east-1. Changing the region requires",
    "# updating NOVA_MODEL_ID below to use the correct regional prefix.",
    "#",
    "# Type    : string (AWS region code, e.g. us-east-1, eu-west-1)",
    "# Default : us-east-1",
    "# Required: yes",
    "# ---------------------------------------------------------------------------",
    "AWS_REGION=us-east-1",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# AWS - Authentication",
    "# ---------------------------------------------------------------------------",
    "# Choose ONE authentication method. Do not set both simultaneously.",
    "#",
    "# Option A: IAM user access keys",
    "#   Suitable for: local dev, CI runners without OIDC support.",
    "#   Required IAM permissions:",
    "#     bedrock:InvokeModel",
    "#     bedrock:InvokeModelWithResponseStream",
    "#   Obtain from: AWS Console > IAM > Users > Security credentials",
    "#",
    "# Option B: Named AWS profile (recommended for local development)",
    "#   Suitable for: developers using aws configure, AWS SSO, or aws-vault.",
    "#   Set AWS_PROFILE to a profile in ~/.aws/credentials or ~/.aws/config.",
    "#   Comment out the Option A variables when using this approach.",
    "#",
    "# Production (ECS Fargate):",
    "#   Neither option applies. Credentials come from the ECS task IAM role",
    "#   defined in terraform/iam_ecs.tf. No credentials are stored in any",
    "#   environment variable for Bedrock access in production.",
    "# ---------------------------------------------------------------------------",
    "",
    "# Option A - IAM access keys (comment out when using Option B)",
    "AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID_HERE",
    "AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY_HERE",
    "",
    "# Option B - Named AWS profile (uncomment and fill in; comment out Option A)",
    "# AWS_PROFILE=your-profile-name",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# Amazon Bedrock - Model Identifiers",
    "# ---------------------------------------------------------------------------",
    "# NOVA_MODEL_ID",
    "#   Cross-region inference profile for Amazon Nova 2 Lite.",
    "#   The 'us.' prefix routes through the US cross-region profile, providing",
    "#   automatic capacity failover across us-east-1 and us-west-2.",
    "#",
    "#   Before making any API call, enable model access in the Bedrock console:",
    "#   https://console.aws.amazon.com/bedrock/home#/modelaccess",
    "#",
    "#   Type    : string (Bedrock cross-region inference profile ID)",
    "#   Default : us.amazon.nova-2-lite-v1:0",
    "#   Required: yes",
    "#",
    "# NOVA_EMBEDDINGS_MODEL_ID",
    "#   Model ID for multimodal embeddings. Reserved for future semantic",
    "#   search and RAG features. Not active in the current release (v0.1).",
    "#",
    "#   Type    : string (Bedrock model ID)",
    "#   Default : amazon.nova-2-multimodal-embeddings-v1:0",
    "#   Required: no",
    "# ---------------------------------------------------------------------------",
    "NOVA_MODEL_ID=us.amazon.nova-2-lite-v1:0",
    "NOVA_EMBEDDINGS_MODEL_ID=amazon.nova-2-multimodal-embeddings-v1:0",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# API - CORS Allowed Origins",
    "# ---------------------------------------------------------------------------",
    "# Comma-separated list of origins permitted to make cross-origin requests",
    "# to the FastAPI backend (/api/* endpoints).",
    "#",
    "# Security rationale (OWASP A05:2021 - Security Misconfiguration):",
    "#   A wildcard (*) bypasses the Same-Origin Policy and exposes every endpoint",
    "#   to requests from arbitrary domains, enabling CSRF attacks. Always use",
    "#   explicit origins. The application rejects wildcards at startup.",
    "#",
    "# Local development:",
    "#   Streamlit runs on port 8501 by default.",
    "#",
    "# Production:",
    "#   Replace with your CloudFront domain (no trailing slash):",
    "#   CORS_ALLOWED_ORIGINS=https://d1abc123example.cloudfront.net",
    "#",
    "#   Multiple origins (comma-separated, no spaces between entries):",
    "#   CORS_ALLOWED_ORIGINS=https://d1abc.cloudfront.net,https://koda.example.com",
    "#",
    "# Type    : string (comma-separated origin URLs, no trailing slashes)",
    "# Default : http://localhost:8501",
    "# Required: yes - must not be empty or contain *",
    "# ---------------------------------------------------------------------------",
    "CORS_ALLOWED_ORIGINS=http://localhost:8501",
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# Session Management",
    "# ---------------------------------------------------------------------------",
    "# SESSION_TIMEOUT_MINUTES",
    "#   Inactivity duration (minutes) after which an in-memory session is",
    "#   marked expired and eligible for cleanup on the next request cycle.",
    "#",
    "#   Sessions are never written to disk or a database. This controls only",
    "#   the in-process TTL. A shorter value limits exposure if a running",
    "#   process is compromised (privacy by design - no persistent user data).",
    "#",
    "#   Type    : integer (minutes, must be > 0)",
    "#   Default : 30",
    "#   Required: no",
    "# ---------------------------------------------------------------------------",
    "SESSION_TIMEOUT_MINUTES=30",
]

content = "\n".join(LINES) + "\n"
TARGET.write_text(content, encoding="utf-8")
print(f"Written: {TARGET} ({len(LINES)} lines)", file=sys.stdout)
